### ISSUE TITLE
Support Gnome 3.16

### ISSUE THREAD

**Issue by kaptoxic** [pulb/mailnag-gnome-shell#16]
Hopefully should not be much more than small changes to metadata.json...

**Comment by pulb** [comment]
Due to the new notification system there are actually a few more changes required than just edititing metadata.json. But I'm planning to fix it as soon as I find time :-)

**Comment by geerds** [comment]
Is there some sort of migration guide for the 3.16 API? Couldn't find anyting

**Comment by geerds** [comment]
I just tested the extension with 3.16. The extension seems to work after adding 3.16 support in the metadata.json except that the top panel icon is only visible if there are unread mails. Is this the normal behavior? (I didn't use the extension in prior versions)

Also note that I didn't test avatars so I don't know if they work with 3.16

**Comment by kparal** [comment]
> I just tested the extension with 3.16. The extension seems to work after adding 3.16 support in the metadata.json except that the top panel icon is only visible if there are unread mails. Is this the normal behavior? (I didn't use the extension in prior versions)

Yes, that's normal.

@pulb , could you simply update the metadata, because it seems to work, and do some more changes in the future, so that people have at least the basic version working now? Thanks a lot.

**Comment by pulb** [comment]
Hi, I moved to a new town and I currently don't have access to my development machine. I'll continue to work on Mailnag and the GS extension as soon as things get back to normal :)

**Comment by entodoays** [comment]
I can confirm that simply modifying the manifest.json file makes the extension work perfectly as with Gnome 3.14.

**Comment by pulb** [comment]
Will fix this as soon as I'm back from my holidays, sorry for the delay.

**Comment by geerds** [comment]
:beers:
