### ISSUE TITLE
The service is not working for Yahoo! accounts?

### ISSUE THREAD

**Issue by madjoe** [pulb/mailnag-gnome-shell#17]
I just wanted to test Mailnag for the first time (since there's no Popper for my Ubuntu 15.04), and unfortunately my Yahoo! account is not working with it. Mailnag works with Gmail just fine, but it fails with Yahoo.

BTW, I think that the blue envelope icon notification within the top panel would be appropriate for this purpose. 

Thanks!

**Comment by madjoe** [comment]
I've just noticed a screenshot of Mailnag here and there's nothing like that on my screen. I can only hear the sound notifications and the result of a 'notify-send' for my new Gmail messages only. Nothing else. I would love to see it in action like on the screenshot.

I installed Mailnag yesterday, from the Software Center.

**Comment by madjoe** [comment]
Ok, I've resolved the icon notification part with "sudo apt-get install mailnag-unity-plugin", which clearly means I'm in a wrong thread (since this one is for Gnome), sorry for that.

My original issue still remains: Yahoo email notifications seem not to work.

**Comment by pulb** [comment]
Please post the contents of ~/.config/mailnag/mailnag.cfg and the debug output printed when starting mailnag in a terminal.

**Comment by madjoe** [comment]
Sure. This is the content of my mailnag.cfg file (I just replaced my real usernames, that's all):
http://privatepaste.com/710b760892

And this is the output when starting mailnag in a terminal:
http://privatepaste.com/eb52840dcc

**Comment by pulb** [comment]
Ok, I read somewhere that yahoo! does not use standard IMAP IDLE notifications. Please try the following:
- Reopen your yahoo account in mailnag-config
- Change "Yahoo" into "Other (IMAP)"
- Untick the Push-IMAP checkbox

**Comment by pulb** [comment]
You can also try to untick the SSL checkbox. If it still does not work either the password is wrong or your yahoo account is configured to use 2-factor authorization.

**Comment by madjoe** [comment]
I just did exactly what you write and the result is this:

File mailnag.cfg has changed only within the line idle = 1 into idle = 0 for my Yahoo account.

This time the output from the terminal is almost identically the same, except for now I can't see the very last line and the second last line from my previous pastebin.

It seems it just doesn't work.

**Comment by pulb** [comment]
Then  most probably the password is wrong or your yahoo account is configured to use 2-factor authorization.

**Comment by madjoe** [comment]
Ah! You're absolutely right.. sorry! I just checked and I don't have 2-factor authorization enabled, so my password was wrong. I created a new password and now everything's fine, even with the Push-IMAP checkbox ticked.

Anyway, probably there's a room for usability improvement - to inform a user that something's wrong when connecting to certain account, no?

Thanks for your help! :)

**Comment by pulb** [comment]
The current development version has a more verbose debug output so in the future it should be easier to track down those connection problems :-)
