### ISSUE TITLE
Update for GNOME 3.18

### ISSUE THREAD

**Issue by kparal** [pulb/mailnag-gnome-shell#19]
Hello,

GNOME 3.18 has been released and many people already use it. Could you please update your extension at extensions.gnome.org to support this new GNOME version?

Thanks!

**Comment by pulb** [comment]
Hi, I'm going to to prepare a 3.18 release as soon as GNOME 3.18 hits the Arch repos.

**Comment by kparal** [comment]
I have [disabled version checking](http://worldofgnome.org/an-easy-way-to-test-extensions-compatibility-in-gnome-3-12/) and your extension seems to work perfectly with GNOME 3.18.

**Comment by pulb** [comment]
Great :) The popup banner code probably need an overhaul though.

**Comment by kparal** [comment]
Works for me. When a new mail arrives, a notification appears. When I hit `Mark all read` in the extension, the notification disappears from the list. The only issue is that I have configured gnome-gmail to open gmail in my browser for email links. And if I click on core mailnag notifications, it does. When I click on email in the mailnag extension, it does. But when I click on notification produced by the mailnag extension, nothing happens.

**Comment by pulb** [comment]
Fixed, will upload a new release to extensions.gnome.org soon.
