### ISSUE TITLE
No Indicator in Ubuntu 15.10

### ISSUE THREAD

**Issue by Feichtmeier** [pulb/mailnag-gnome-shell#22]
Hi! 
Thanks for mailnag! It is really fast :)

Though I did install mailnag via sudo apt-get install mailnag
and then installed the unity plugin from your tarball the indicator did not show up.

I then entered "mailnag-unity.desktop" manually in dconf > com > canonical > indicator > messages and it shows up. But it does not change indicate new messages. "Only" the popup in unity is working.

Thanks in advance!

**Comment by pulb** [comment]
Hi and thanks for your bugreport.
I rebuilt the unity-plugin package for Ubuntu 15.10 in the mailnag ppa - please check if it works for you.

**Comment by Feichtmeier** [comment]
Wow thanks for the fast reply!

  

The installation works now with apt-get :)

  

But! The indicator still doesn't work.

Should I maybe purge it completly and reinstall it?

  

The unity message still works super fast though =)

> On Nov 8 2015, at 2:27 pm, Patrick Ulbrich &lt;notifications@github.com&gt;
wrote:  

>

> Hi and thanks for your bugreport.  
I rebuilt the unity-plugin package for Ubuntu 15.10 in the mailnag ppa -
please check if it works for you.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/pulb
/mailnag-gnome-shell/issues/22#issuecomment-154826506).![](https://github.com/
notifications/beacon/AOno1jpSqX10WKUMgmFpzGXwmu0T9TATks5pD0U1gaJpZM4GeCAo.gif)

**Comment by pulb** [comment]
Yes, please remove everything you installed by hand and reinstall the package. Also make sure you enabled the unity plugin in mailnag-config. If it still doesn't work please start mailnag from a terminal and check if there are any error messages.

**Comment by Feichtmeier** [comment]
Yay! That worked! :)  
Oh dear finally! Nylas N1 \+ mailnag = gtfo my computer dear
thunderbird/evolution!  
Thanks mate!!!

> On Nov 8 2015, at 3:00 pm, Patrick Ulbrich &lt;notifications@github.com&gt;
wrote:  

>

> Yes, please remove everything you installed by hand and reinstall the
package. Also make sure you enabled the unity plugin in mailnag-config. If it
still doesn't work please start mailnag from a terminal and check if there are
any error messages.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/pulb
/mailnag-gnome-shell/issues/22#issuecomment-154828329).![](https://github.com/
notifications/beacon/AOno1r3HD2D-FbhiLBeVN07rjxcIWzAYks5pD0z9gaJpZM4GeCAo.gif)

**Comment by pulb** [comment]
You're welcome :-)
