### ISSUE TITLE
Trim mail subject

### ISSUE THREAD

**Issue by HeikoAdams** [pulb/mailnag-gnome-shell#23]
The subject line is currently not trimmed which causes the list of mails look like this if a mail has a very long subject 
![bildschirmfoto von 2015-12-21 15-23-47](https://cloud.githubusercontent.com/assets/1418818/11932789/2383d83a-a7f8-11e5-952b-9a8dc888b6dd.png)

**Comment by pulb** [comment]
I really don't see what's wrong with that :grin:

**Comment by pulb** [comment]
Related to isssue #15

**Comment by pulb** [comment]
Fixed in commit 03a166f.
