### ISSUE TITLE
gschemas.compiled: open() failed: File or directory doesn't exist

### ISSUE THREAD

**Issue by kparal** [pulb/mailnag-gnome-shell#27]
After latest update from https://extensions.gnome.org/extension/886/mailnag/ mailnag no longer works for me, the installation button on that page displays `ERROR` and I see this in console:

> Mar 29 15:03:25 dryad gnome-shell.desktop[1970]: Gjs-Message: JS LOG: Extension "mailnag@pulb.github.com" had error: GLib.FileError: Can't open file „/home/kparal/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas/gschemas.compiled“: open() failed: File or directory doesn't exist

**Comment by pulb** [comment]
Ooops.. I guess I forgot to include the gschemas.compiled file :\
As quick fix run `glib-compile-schemas /home/kparal/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas/`

Thanks for reporting!

**Comment by pulb** [comment]
Fixed.

**Comment by pulb** [comment]
Fixed again. Thanks for reporting.
