### ISSUE TITLE
Mailnag Extension does not start Automatically

### ISSUE THREAD

**Issue by kyleamadio** [pulb/mailnag-gnome-shell#28]
On my Ubuntu Gnome 16.04, I have to start Mailnag manually from the extensions tool after each reboot and after inactivity or suspend.

This version of Mailnag came from the Ubuntu repositories.

![mailnag](https://cloud.githubusercontent.com/assets/1647986/14235314/56519408-fa3e-11e5-9e87-80841377eb32.png)

![mailnag2](https://cloud.githubusercontent.com/assets/1647986/14235321/91e09546-fa3e-11e5-9bb7-1eef1a19b002.png)

![mailnag3](https://cloud.githubusercontent.com/assets/1647986/14235323/98778450-fa3e-11e5-88d3-e65831653c51.png)

**Comment by kyleamadio** [comment]
I found a work around, if I copied the directory 

/usr/share/gnome-shell/extensions/mailnag@pulb.github.com 

to ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com 

the extension auto starts correctly.

**Comment by pulb** [comment]
Please remove the extension fom *.local/share/gnome-shell/extensions*, reboot and if it isn't working check if there are any mailnag extension errors by running `journalctl -b | grep gnome-session ` in a terminal.

**Comment by pulb** [comment]
Oh... and I would really appreciate it if you could share your findings with me :wink:

**Comment by pulb** [comment]
Closed due to lack of information.
