### ISSUE TITLE
don't work with gnome 3.20 (outdated)

### ISSUE THREAD

**Issue by hoellen** [pulb/mailnag-gnome-shell#30]
gnome says 'outdated' if I want to install it in the new gnome 3.20 version.

**Comment by hoellen** [comment]
added version 3.20 in metadata.json
`"shell-version": [
    "3.16", 
    "3.18",
    "3.20"
  ],`
and everything works fine!

**Comment by Wabuo** [comment]
Hey culd you also please relese an new version vor 3.20.

Thx Wabuo

**Comment by pulb** [comment]
Fixed.
