### ISSUE TITLE
Fedora 24. Extension icon doesn't show in the statusbar

### ISSUE THREAD

**Issue by proninyaroslav** [pulb/mailnag-gnome-shell#34]
Hello. I install extension using [extensions.gnome.org](https://extensions.gnome.org/). But on Fedora 24 (Gnome 3.20.1) icon in the statusbar is not available.

**Comment by pulb** [comment]
Die you enable the extension in gnome-tweak-tool and restarted gnome-shell?

**Comment by pulb** [comment]
Oh and more importantly make sure the [mailnag daemon](https://github.com/pulb/mailnag) is properly configured and running 
(run `mailnag-config`).
