### ISSUE TITLE
Custom gnome-shell icon

### ISSUE THREAD

**Issue by edgard** [pulb/mailnag-gnome-shell#35]
Hey Patrick! First of all, great work. I have a suggestion on the gnome-shell tray icon:

Depending on the theme you're using, the default icon for read/unread messages seems to be out of place, it would be nice if we had the option to select a custom icon and opacity settings in this case.

**Comment by pulb** [comment]
Hey edgard,

I just [verified it](https://github.com/pulb/mailnag-gnome-shell/blob/master/indicator.js) - the extension references the `mail-unread-symbolic` icon, so if your custom theme does not override that one, there's nothing I can do abou it.
