### ISSUE TITLE
Update for Gnome 3.21.x and 3.22

### ISSUE THREAD

**Issue by tikank** [pulb/mailnag-gnome-shell#36]
It seems that Debian is updating Gnome to new version. Gnome Shell version 3.21.91 arrived to Debian testing and apparently version 3.22 will come in near future.

mailnag-gnome-shell will need at least version number update.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836207

**Comment by tikank** [comment]
I added 3.21.91 to the shell-version list. The extension seems to work normally and without failures.

**Comment by pulb** [comment]
Good to know, thanks. I'll add 3.22 to the version list as soon as GNOME 3.22 has been released.

**Comment by pulb** [comment]
Fixed in commit e146dced3125bba3e53a058435d71251d5d8729d.
