### ISSUE TITLE
mailnag-gnome-shell  avatar issue

### ISSUE THREAD

**Issue by tjw0lf** [pulb/mailnag-gnome-shell#37]
avatars not showing up for me. 
Please check this out to see if its still working fantastic work please keep this updated amazing

Is there any kind of trouble shooting we can do. If not in thew mean time i will check  manajro Arch and see if it works in there real quick. I will install it just to see if its not openSUSE tumbleweed at all

**Comment by pulb** [comment]
Fixed in git. Please test.

**Comment by tjw0lf** [comment]
OK sorry i was out. 
Which one do i need to redownload and install the gnome.shell one

**Comment by tjw0lf** [comment]
i downloaded the mailnag-gnome-shell again and installed it. avatars still not showing up in the panel.

Please write me the right step as to how this should be done.

**Comment by pulb** [comment]
```
rm -rf ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com
cd your-mailnag-git-folder
make install-local
```
After that
- Make sure you've got an `aggregate-avatars` executable in ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com
- Add an avatar to the account you're sending mails from
- Restart gnome-shell
- Make sure avatars are enabled in the extension settings

**Comment by tjw0lf** [comment]
Here's my two avatars i'm using so you know they both have avatars.

used my chicknfangz email to send to my wolf gmail account.

The avatar still are not showing up here's some screenshots

[URL=http://www.imagebam.com/image/bd4b0e507016957][IMG]http://thumbnails115.imagebam.com/50702/bd4b0e507016957.jpg[/IMG][/URL] 

[URL=http://www.imagebam.com/image/99107c507016959][IMG]http://thumbnails115.imagebam.com/50702/99107c507016959.jpg[/IMG][/URL] 

[URL=http://www.imagebam.com/image/bbd838507016962][IMG]http://thumbnails115.imagebam.com/50702/bbd838507016962.jpg[/IMG][/URL]

**Comment by pulb** [comment]
Strange.. libfolks-eds* is still installed? What's the output of aggregate-avatars if you run it in a terminal?

**Comment by pulb** [comment]
Maybe aggregate-avatars is not in your PATH. Please try to create a symlink in /usr/local/bin.

sudo ln -s ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/aggregate-avatars /usr/local/bin/aggregate-avatars

**Comment by tjw0lf** [comment]
nope still not avatars

i get this when put in terminal
tj@wolf:~> aggregate-avatars
If 'aggregate-avatars' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf aggregate-avatars

**Comment by pulb** [comment]
Please post the contents of aggregate-avatars.vala and execute
"~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/aggregate-avatars" in a terminal

**Comment by tjw0lf** [comment]
where did you want me to look for this at.  contents of aggregate-avatars.vala and execute

**Comment by tjw0lf** [comment]
I'm i putting this in right??
tj@wolf:~> "~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/aggregate-avatars" 
bash: ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/aggregate-avatars: No such file or directory
tj@wolf:~>

**Comment by pulb** [comment]
No, please try the following and post the complete output of all commands:
cd  ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com
ls -la
./aggregate-avatars
cat aggregate-avatars.vala

Am 1. Oktober 2016 04:43:09 MESZ, schrieb TJ Wolf <notifications@github.com>:

**Comment by tjw0lf** [comment]
tj@wolf:~> cd  ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com> ls -la
total 88
drwxr-xr-x  3 tj users  4096 Sep 29 17:21 .
drwxr-xr-x 19 tj users  4096 Sep 29 17:21 ..
-rwxr-xr-x  1 tj users 23040 Sep 29 17:21 aggregate-avatars
-rw-r--r--  1 tj users  3723 Sep 29 17:21 convenience.js
-rw-r--r--  1 tj users 10543 Sep 29 17:21 extension.js
-rw-r--r--  1 tj users 13532 Sep 29 17:21 indicator.js
-rw-r--r--  1 tj users   260 Sep 29 17:21 metadata.json
-rw-r--r--  1 tj users  1197 Sep 29 17:21 opts.js
-rw-r--r--  1 tj users  3847 Sep 29 17:21 prefs.js
drwxr-xr-x  2 tj users  4096 Sep 29 17:21 schemas
-rw-r--r--  1 tj users  1762 Sep 29 17:21 stylesheet.css
-rw-r--r--  1 tj users  1272 Sep 29 17:21 utils.js
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com> ./aggregate-avatars

(process:6942): Tracker-WARNING **: tracker-backend.vala:211: Falling back to bus backend, the direct backend failed to initialize: Locale mismatch, cannot use direct connection

(process:6942): eds-WARNING **: edsf-persona-store.vala:2588: Error in address book view query: Authentication required
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com> cat aggregate-avatars.vala
cat: aggregate-avatars.vala: No such file or directory
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com>

**Comment by pulb** [comment]
There you go:
"edsf-persona-store.vala:2588: Error in address book view query: Authentication required"

Somehow the extension does not have the rights to access your gnome-contacts address-book.

**Comment by pulb** [comment]
Please try to disable Google/Google+ and possible other accounts in gnome-online-accounts. Please also post the contents of aggregate-avatars.vala (in the directory you compiled the extension from)

**Comment by tjw0lf** [comment]
Why disable google+ ??  Its not even showiing for google+ avatars either. shouldn't it be showing for google+ two avatars.

**Comment by tjw0lf** [comment]
how do i do this i don't follow sorry

post the contents of aggregate-avatars.vala (in the directory you compiled the extension from)

**Comment by tjw0lf** [comment]
OK there was no accounts in the gnome accounts" so i added mine and another one i use

And i did the command again
tj@wolf:~> cd  ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com> ls
aggregate-avatars  extension.js  metadata.json  prefs.js  stylesheet.css
convenience.js     indicator.js  opts.js        schemas   utils.js
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com> ls -la
total 88
drwxr-xr-x  3 tj users  4096 Sep 29 17:21 .
drwxr-xr-x 19 tj users  4096 Sep 29 17:21 ..
-rwxr-xr-x  1 tj users 23040 Sep 29 17:21 aggregate-avatars
-rw-r--r--  1 tj users  3723 Sep 29 17:21 convenience.js
-rw-r--r--  1 tj users 10543 Sep 29 17:21 extension.js
-rw-r--r--  1 tj users 13532 Sep 29 17:21 indicator.js
-rw-r--r--  1 tj users   260 Sep 29 17:21 metadata.json
-rw-r--r--  1 tj users  1197 Sep 29 17:21 opts.js
-rw-r--r--  1 tj users  3847 Sep 29 17:21 prefs.js
drwxr-xr-x  2 tj users  4096 Sep 29 17:21 schemas
-rw-r--r--  1 tj users  1762 Sep 29 17:21 stylesheet.css
-rw-r--r--  1 tj users  1272 Sep 29 17:21 utils.js
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com> ./aggregate-avatars
(process:5603): Tracker-WARNING **: tracker-backend.vala:211: Falling back to bus backend, the direct backend failed to initialize: Locale mismatch, cannot use direct connection
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com> cat aggregate-avatars.vala
cat: aggregate-avatars.vala: No such file or directory
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com>

**Comment by pulb** [comment]
aggregate-avatars.vala is located in the folder you got from github.  The folder you ran "make install-local" in. So do the following:

cd location-of-your-github-folder
cat aggregate-avatars.vala

**Comment by tjw0lf** [comment]
OK i'm confused. Up top you wanted me to check for  "aggregate-avatars." before So i rechecked the files you had and there's nothing for that file. Its only "aggregate-avatars.vala" Not both. So i redownload the github mailnag-gnome-shell. And i have "aggregate-avatars.vala" now.  Before it was "aggregate-avatars" not both

**Comment by tjw0lf** [comment]
I'm getting that error when first started again

**Comment by tjw0lf** [comment]
You didn't fix anything or change anything pulb. I'm getting this again LOL

GLib.FileError: Failed to open file '/home/tj/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  getSettings@/home/tj/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/convenience.js:81
  MailnagSettingsWidget<._init@/home/tj/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/prefs.js:46
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/tj/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/prefs.js:99
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1

**Comment by tjw0lf** [comment]
OK fixed it again. That need to be fixed thats annoyance pulb......

**Comment by tjw0lf** [comment]
tj@wolf:~> cd ~/.local/share/gnome-shell/extensions/mailnag\@pulb.github.com/
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com> ls -la
total 100
drwxrwxr-x  3 tj users  4096 Sep 29 12:56 .
drwxr-xr-x 19 tj users  4096 Oct  2 12:51 ..
-rw-rw-r--  1 tj users  1792 Sep 29 12:56 aggregate-avatars.vala
-rw-rw-r--  1 tj users  3723 Sep 29 12:56 convenience.js
-rw-rw-r--  1 tj users 10543 Sep 29 12:56 extension.js
-rw-rw-r--  1 tj users    38 Sep 29 12:56 .gitignore
-rw-rw-r--  1 tj users 13532 Sep 29 12:56 indicator.js
-rw-rw-r--  1 tj users 18092 Sep 29 12:56 LICENSE
-rw-rw-r--  1 tj users  1471 Sep 29 12:56 Makefile
-rw-rw-r--  1 tj users   260 Sep 29 12:56 metadata.json
-rw-rw-r--  1 tj users  1197 Sep 29 12:56 opts.js
-rw-rw-r--  1 tj users  3847 Sep 29 12:56 prefs.js
-rw-rw-r--  1 tj users  2109 Sep 29 12:56 README.md
drwxrwxr-x  2 tj users  4096 Oct  2 13:01 schemas
-rw-rw-r--  1 tj users  1762 Sep 29 12:56 stylesheet.css
-rw-rw-r--  1 tj users  1272 Sep 29 12:56 utils.js
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com>

**Comment by tjw0lf** [comment]
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com> cat aggregate-avatars.vala
/* Mailnag - GNOME-Shell extension frontend
*
* Copyright 2013, 2016 Patrick Ulbrich <zulu99@gmx.net>
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
*/

/* This tool aggregates a list of (email, avatar_file) pairs 
 * which is passed to the Mailnag GNOME-Shell extension. 
 * Compile with `valac --pkg folks aggregate-avatars.vala`. 
 */
 
using Folks;

MainLoop mainloop = null;

void main()
{
	mainloop = new MainLoop();

	var aggregator = IndividualAggregator.dup();
	aggregator.prepare();
	
	Idle.add(() => {
		if (!aggregator.is_quiescent)
			return true;
		
		var sb = new StringBuilder();
		
		foreach (var e in aggregator.individuals.entries)
		{
			Individual individual = e.value;
			FileIcon file_icon = individual.avatar as FileIcon;
			
			if (file_icon != null)
			{
				File file = file_icon.get_file();
				
				if (file.query_exists())
				{	
					foreach (var email in e.value.email_addresses)
						sb.append_printf("%s;%s;", email.value.strip(), file.get_path());
				}
			}	
		}
		
		stdout.printf(sb.truncate(sb.len - 1).str);
		stdout.flush();
		mainloop.quit();
		
		return false;
	});
	
	mainloop.run();
}
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com>

**Comment by pulb** [comment]
aggregate-avatars is not there because it is generated by make install-local.. would you please post the contents of aggregate-avatars.vala now?

**Comment by pulb** [comment]
Ok, that's the fixed version of aggregate-avatars.vala. That really should work. If you entered the correct email address in gnome-contacts I have really no idea what's wrong. I'ts working fine on my system. You could try to assign the emails address to other email fields (private, work,..) in gnome-contacts.

**Comment by tjw0lf** [comment]
I'm not getting the avatars at all on the panel not even for G+. As i showed you the screenshots in past post before. Still nothing??

As you can see both accounts has avatars

http://www.imagebam.com/image/56d3e7507490582


What system OS are you running? 

Can you post screenshot of yours working please?

**Comment by pulb** [comment]
I tested it in Ubuntu 16.04 and Arch Linux.

![aggregate-avatars](https://cloud.githubusercontent.com/assets/827576/19034806/e8bf1ae8-8965-11e6-9030-60b6a7dffa64.png)

**Comment by tjw0lf** [comment]
I have a feeling its openSUSE! and security or privacy. I will try on Arch....let you know

How come my name isn't showing avatar?

**Comment by pulb** [comment]
I've got that feeling to..

Why should it show your avatar? I don't have your email address in any of my address books nor did I associate an avatar to it.

**Comment by tjw0lf** [comment]
haha yeah. Put my email in see if it works show me? You don't have to set avatar for me i already have one

Oh wait where do we put the avatars at. Is it supposed to be in a certain folder? for mailnag

**Comment by pulb** [comment]
No, I won't try it with your email. I already spent too much time on this. It's working, trust me.

It doesn't matter where you choose the avatars from. They are copied to a hidden settings folder.

**Comment by pulb** [comment]
I've rewritten the avatar aggregation code. Maybe this solves your problems.

**Comment by tjw0lf** [comment]
Cool.. How should i install it. do i just re download it over top.

**Comment by tjw0lf** [comment]
nope nothing still. Its openSUSE i think got the feeling.

I'm going to be installing GNOME ARCH so i will let you know if i'm getting it on there or not

Also you might want to fix these error is annoyance everytime redownload the mailnag-gnome-shell

 always having to do this
cd ~/.local/share/gnome-shell/extensions/mailnag\@pulb.github.com/schemas

glib-compile-schemas .

**Comment by pulb** [comment]
Yes, delete the installed extension, redownload the latest git commit and re-run `make install-local`.

(glib-compile-schemas is not required as it is triggered by make)

**Comment by pulb** [comment]
Installing the extension via copy and paste is not recommended. As stated in the readme you have to use `make install-local`. Otherwise the compiled schemas file and avatar support is missing.

**Comment by tjw0lf** [comment]
**Awesome**
I did like you said re-downloaded git-clone `make install-local`
avatars show up now!!! whoop whoop rewriting it fixed it Thanks million :D

**Comment by pulb** [comment]
Pheeew.. finally :)

If you own an Android phone and you enable the Google account in gnome-online-accounts, it should sync the photos of your phone's address-book as well.

**Comment by tjw0lf** [comment]
I know...right. about time :)

where does it place those photos" I already have them enabled

**Comment by pulb** [comment]
`ls -la /run/user/$UID/aggregate-avatars-cache/`
The contacts in the address-book of course need to have an email address.

**Comment by tjw0lf** [comment]
i have this
tj@wolf:~> ls -la /run/user/$UID/aggregate-avatars-cache/
total 68
drwxr-xr-x  2 tj users  360 Oct  8 09:49 .
drwx------ 13 tj users  260 Oct  8 10:27 ..
-rw-------  1 tj users 2122 Oct  8 09:49 1dea42b58a17a46c93f8006feaaae593618c4aa0
-rw-------  1 tj users 1264 Oct  8 09:49 23460cb967216a171c5a6209d9027a1f845b5166
-rw-------  1 tj users 3137 Oct  8 09:49 26989a10722654c3d995c1201e0a92daf32d40c8
-rw-------  1 tj users 1691 Oct  8 09:49 28f782c1d96b10e37b83427f6ad03ade361c06d0
-rw-------  1 tj users 4262 Oct  8 09:49 39b9f18907b480209914e9ec57177fa560a57a9c
-rw-------  1 tj users 1305 Oct  8 09:49 4e37b5b97aee7c67d7850d01047547befa0f9703
-rw-------  1 tj users 2339 Oct  8 09:49 5ccddceb974048761628425ae4f3d133c2e9b48f
-rw-------  1 tj users 2180 Oct  8 09:49 646d529eee189f49fb439ef17da67f6310acfe72
-rw-------  1 tj users 2758 Oct  8 09:49 6d308745e7915006e404e133a9d03ebcc009518d
-rw-------  1 tj users 1986 Oct  8 09:49 796e165f16694315f35ac08dd13b733b741787fa
-rw-------  1 tj users 3775 Oct  8 09:49 89755dc3dd40c97149686909f874aeb1e97f4cdf
-rw-------  1 tj users 1756 Oct  8 09:49 8ce09356b331f2a505ac78536eaaa88f7cfc54ec
-rw-------  1 tj users 3417 Oct  8 09:49 8da4fd5d9d82072b60948f08f4144eeebe748cec
-rw-------  1 tj users 2976 Oct  8 09:49 9298a46f87921ff1b2cf49dd3bef7d6526288f19
-rw-------  1 tj users 2087 Oct  8 09:49 c96f7a177ef6ce82df858d2eac0c4233caaea589
-rw-------  1 tj users 3542 Oct  8 09:49 ee39152fbe5b71172a201ac0c1c9a401474a620d
tj@wolf:~>

**Comment by pulb** [comment]
Yeah, if you open this folder in nautilus you see the actual images
`nautilus /run/user/$UID/aggregate-avatars-cache/`

**Comment by tjw0lf** [comment]
its showing avatars from people. not pictures from my phone

**Comment by pulb** [comment]
Uhhmm yeah. Of cource it's showing avatars/photos from people. Why do you expect it to show picture of your phone???

**Comment by tjw0lf** [comment]
You said it showed pictures on my phone?? LOL

"If you own an Android phone and you enable the Google account in gnome-online-accounts, it should sync the photos of your phone's address-book as well."

NO pictures from my phone

**Comment by pulb** [comment]
Yes, I said 
> the photos of your phone's address-book 

What are we talking about here, the photos of your phone's address-book ot the pictures of your phone (camera)?

**Comment by tjw0lf** [comment]
Oh OK i see lol.

I thought you meant photos of my phones gallery photos...

**Comment by pulb** [comment]
Well, that makes little sense..
