### ISSUE TITLE
Disabled, Mailnag still works

### ISSUE THREAD

**Issue by freeroot** [pulb/mailnag-gnome-shell#40]
When I'm on my pc with friends, I would like to disable Mailnag for a moment.

But it goes on giving me gnome notifications even when Mailnag is disabled (see the button at the bottom of the screenshot).

![screenshot tue dec 20 2016 11 43 43 gmt 0100 cet 389x478](https://cloud.githubusercontent.com/assets/20989929/21347610/ac0a49e8-c6a9-11e6-95bd-a5297c6891a9.png)

**Comment by pulb** [comment]
Did you close that dialog after toggling the switch?

**Comment by freeroot** [comment]
Yes. Shouldn't I ?

**Comment by pulb** [comment]
Closing is necessary for config changes to take effect. Please run mailnag-config in terminal, turn the switch on/off, close the window and check what the terminal output says.

**Comment by freeroot** [comment]
It seems to work, I don't know why it didn't work this weekend. Sorry.

**Comment by pulb** [comment]
No need to be sorry, maybe mailnag-config didn't terminate for some reason. Please let me know if you observe this again.

**Comment by freeroot** [comment]
It appears when I disable Mailnag (switch off and close config window) and I reboot my pc. At start, Mailnag is enable because I have notifications. If I just open config window and close it immediately, Mailnag comes back disable (because the switch button is already at off). So it seems to be a boot issue.

**Comment by pulb** [comment]
It seems this setting isn't stored in your ~/.config/autostart/mailnag.desktop file. Where did you get mailnag from? A package repository,  git clone, ...?

**Comment by freeroot** [comment]
From application "software" of gnome.

The file contains : 

[Desktop Entry]
Name=Mailnag
Comment=An extensible mail notification daemon
Comment[de]=Ein erweiterbarer Mail-Benachrichtigungs-Dämon
Keywords=mail;notify;notification;
Exec=/usr/bin/mailnag --quiet
Icon=mailnag
Type=Application
NoDisplay=true
X-GNOME-Autostart-enabled=true
X-GNOME-UsesNotifications=true

**Comment by freeroot** [comment]
I think it's an issue of Mailnag (https://github.com/pulb/mailnag).

If I delete manually ~/.config/autostart/mailnag.desktop and then I switch on Mailnag, the file is created and I think it's by _create_autostart() (https://github.com/pulb/mailnag/blob/master/Mailnag/configuration/configwindow.py#L277), so I believe _create_autostart() works fine.

But _delete_autotart() (https://github.com/pulb/mailnag/blob/master/Mailnag/configuration/configwindow.py#L298) is there to delete the file but because the file is not deleted, I think the issue is here.

**Comment by freeroot** [comment]
I open an parallele issue at https://github.com/pulb/mailnag/issues/147

**Comment by pulb** [comment]
Fixed, thanks for the pull request :)
