### ISSUE TITLE
Crash during startup with gnome-shell 3.24

### ISSUE THREAD

**Issue by jdoe0** [pulb/mailnag-gnome-shell#44]
With gnome-shell 3.24, the extension crashes during startup. The following error message and stack trace appear in the log.

````
JS ERROR: Exception in callback for signal: extension-found: TypeError: redeclaration of let size
@/home/user/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/extension.js:28:7
initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:221:5
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:168:18
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:304:9
_emit@resource:///org/gnome/gjs/modules/signals.js:126:27
ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:184:9
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
bind/<@resource:///org/gnome/gjs/modules/lang.js:95:16
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:1
ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:189:9
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:306:5
enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:314:9
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:345:9
init@resource:///org/gnome/shell/ui/extensionSystem.js:353:5
_initializeUI@resource:///org/gnome/shell/ui/main.js:219:5
start@resource:///org/gnome/shell/ui/main.js:127:5
@<main>:1:31
````

**Comment by pulb** [comment]
Thanks for your bug report. I'll fix this as soon as GNOME 3.24 hits my distros package repos.

**Comment by 1Claude** [comment]
May I ask what is your distro, @pulb ?

Ubuntu GNOME is coming out next week with 3.24.

**Comment by pulb** [comment]
I'm using arch. Gnome 3.24 should be available in its repos within the next few weeks.

**Comment by jeroenpraat** [comment]
+1

**Comment by elkrejzi** [comment]
And it's finally in [testing]. This is the only extension I'm missing.

**Comment by ronjouch** [comment]
Gnome 3.24 is in the main Arch repos, @pulb hope you find the time to have a look :)

3.24 was a painless upgrade on my intel thinkpad; some [r/Arch users report](https://www.reddit.com/r/archlinux/comments/678rol/gnome_324_is_in_the_official_repo/) various breakages around libgweather, nvidia, openssl/steam/spotify.

**Comment by pulb** [comment]
@ronjouch thanks for the notification :) I'm gonna upgrade next weekend and try to fix the extension if everything goes well :)

**Comment by ronjouch** [comment]
@pulb easy fix, actually. It looks like Gnome activated strict mode for extensions, redeclarations like the ones in `indicator.js` and `extension.js` to become errors rather than warnings. A few grep and rename later for half a dozen `let [foo, size] = someFunction()` into `let [foo, fooSize] = someFunction()`, the extensions works like it used to 😃.

Thanks again for the awwwwesome extension!

**Comment by pulb** [comment]
Oh that's good too know. Now that you mention it, I remember reading somewhere that they upgraded the SeaMonkey JS engine (gjs) to a newer version. I'll have a look asap. Thanks for the pointers!

**Comment by ronjouch** [comment]
@pulb yup, here's the [blog post detailing GNOME 3.24's upgrade to SpiderMonkey 38](https://ptomato.wordpress.com/2017/04/22/javascript-news-from-gnome-3-24/) (read it via Planet GNOME).

Also, unrelated question: do GJS stacktraces always suck that much? On my machine, the suggested cuplrit line (28) had nothing to do with the actual location of the `size` redeclarations 😢.

**Comment by pulb** [comment]
Right, it was spider monkey actually :) Yes this stacktrace sucks, because of this I had no idea what's going on.

Am 24. April 2017 20:28:24 MESZ schrieb Ronan Jouchet <notifications@github.com>:

**Comment by pulb** [comment]
[Fix released](https://github.com/pulb/mailnag-gnome-shell/releases/tag/v3.24.0) and submitted to extensions.gnome.org.
