### ISSUE TITLE
Not working with GNOME Shell 3.24

### ISSUE THREAD

**Issue by shuvo-paul** [pulb/mailnag-gnome-shell#45]
The current version is not working with gnome 3.24. Please update it.

Thanks

**Comment by pulb** [comment]
Sure, it does work with GNOME 3.24. What version are you using and where did you get it from?

**Comment by shuvo-paul** [comment]
I am using antergos. Yesterday I got and error (could not satisfy dependency gstremer0.10) while updating. To solve this issue I manually removed gstreamer0.10 . Then I am getting error loading extensions for mailnag. I thought it was a gnome shell issue. How can I solve this? Should I reinstall gstremer0.10?

Thanks

**Comment by pulb** [comment]
mailnag-gnome-shelll does not depend on gstreamer0.10. Please either use [this](https://aur.archlinux.org/packages/mailnag-gnome-shell/) package or git it from [extensions.gnome.org](https://extensions.gnome.org/extension/886/mailnag/).

**Comment by shuvo-paul** [comment]
I have just update mailnag-gnome-shelll and it is working like charm.

Thanks a lot.
