### ISSUE TITLE
New mail open a new blank page ?

### ISSUE THREAD

**Issue by OSryx** [pulb/mailnag-gnome-shell#46]
When I click on new email, I get blank new page with google chrome. 

$BROWSER = /usr/bin/google-chrome

Please how to fix this ?

**Comment by pulb** [comment]
What program did you install to open new mails in a browser? gnome-gmail?

**Comment by OSryx** [comment]
simply nothing

**Comment by pulb** [comment]
Well, you did. Mailnag itself does not open a browser. It calls the systems standard email client. Please check what email program is set in gnome-control-center -> Details -> Default Applications.

**Comment by OSryx** [comment]
google-chrome

**Comment by pulb** [comment]
Yeah, so GNOME simply opens chrome without an URL if an application requests to open an email reader. You have to use a program like [GNOME Gmail](http://gnome-gmail.sourceforge.net).

**Comment by OSryx** [comment]
thank u
