### ISSUE TITLE
.date-label in stylesheet.css conflicts with .datemenu-today-button .date-label in gnome-shell.css

### ISSUE THREAD

**Issue by cbowman57** [pulb/mailnag-gnome-shell#50]
.date-label duplicates a standard entry in gnome-shell.css causing it to override the calendar date in the shell's dropdown calendar.

My solution was to change .date-label in stylesheet.css and indicator.js to .mailnag-date-label

Additionally I deleted all the color: #8e8e80; entries as it appears those seem to be supplied by the gnome-shell theme for best aesthetic on custom themes.

(I'm using gnome 3.26.2 and 3.27.1, not sure if this appeared in previous versions)

Sep 12 2018, this has still not been addressed.

**Comment by pulb** [comment]
Fixed. Thanks!

**Comment by cbowman57** [comment]
Great.   Thank you.
