### ISSUE TITLE
Checking e-mails doesn't work after update

### ISSUE THREAD

**Issue by kosal75** [pulb/mailnag-gnome-shell#67]
When updating to 2.0.0 (ie. from older Ubuntu version to Ubuntu 20.04 version, at least in my case) checking of e-mails didn't work. After giving in the passwords again for my accounts, it started to work again. Apparenty the new version overrides the passwords given in the old version.

**Comment by pulb** [comment]
yeah, that's because as of version 2.0 mailnag uses libsecret to manage passwords, wheras previous versions were using gnome-keyring.
