### ISSUE TITLE
Add support for GNOME 40

### ISSUE THREAD

**Issue by Kerrung** [pulb/mailnag-gnome-shell#69]

**Comment by vantu5z** [comment]
TypeError: box.add is not a function

Stack trace:
  _init@/home/vantu5z/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/prefs.js:44:7
  buildPrefsWidget@/home/vantu5z/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/prefs.js:94:15
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
