### ISSUE TITLE
Mail subjects with special characters (like German umlauts) are cut off

### ISSUE THREAD

**Issue by hkockerbeck** [pulb/mailnag-gnome-shell#71]
When a mail subject contains a German umlaut, it isn't displayed fully. Instead, the subject is cut off at the end of the previous word. For example, if the subject is

`Wie wär's mit einem lauschigen Sonnenplätzchen?`

the extension only shows

`Wie`

I haven't tested it, but I'd assume it happens with other non-ASCII characters as well. 

I'm using Ubuntu 20.04, Gnome Shell 3.36.7, Mailnag extension latest version provided at extensions.gnome.org.

**Comment by pulb** [comment]
I can't reproduce your issue on Arch linux (neither in gnome 3.38 nor in gnome 40). It's probably a font rendering/pango issue of Ubuntu 20.04.

![screenshot](https://user-images.githubusercontent.com/827576/118279520-88b73180-b4cb-11eb-8870-ba9484d2a396.png)
