### ISSUE TITLE
E-Mail Check Frequency

### ISSUE THREAD

**Issue by sojusnik** [pulb/mailnag-gnome-shell#9]
Hi!

Is there a way to adjust the e-mail check frequency in mailnag and the gnome-shell indicator respectively? The old version, as I can remember, had such an option. Currently, I have to wait several minutes to get a notification in the topbar of a new e-mail. The same goes for a read or deleted e-mail.

Best!

**Comment by sojusnik** [comment]
I've stumbled upon some Firefox addons, that seem to work with labels in connection with instant notification, have a look yourself:

https://addons.mozilla.org/de/firefox/addon/fastest-notifier-for-gmail

https://addons.mozilla.org/de/firefox/addon/gmail-notifier-restartless

Maybe their approach could also be applied to Mailnag?

**Comment by sojusnik** [comment]
Could you make any progress on this issue?

**Comment by pulb** [comment]
Hi sojusnik, I was not able to work on mailnag for the last half year, so no :(

**Comment by sojusnik** [comment]
No big deal.

BTW: Wouldn't it make more sense to move this topic to [mailnag](https://github.com/pulb/mailnag/issues) itself?

**Comment by HoboPrimate** [comment]
When using the g-o-a plugin, should it notify of new e-mails immediately as well? For e-mails arriving on the inbox.

**Comment by pulb** [comment]
@HoboPrimate: Yes you should get instant push notifications for GOA imap accounts.

**Comment by titus65** [comment]
Hi,
the K9 mail android app supports folders and idle, why not mailnag?

**Comment by pulb** [comment]
@titus65 because this project is a one man show. I'm working on Mailnag in my freetime which is very limited. I simly didn't find the time to look into this issue yet and since I'm not using folders personally, it has a pretty low priority on my TODO list THB.

**Comment by pulb** [comment]
I moved this conversation [to the Mailnag main project](https://github.com/pulb/mailnag/issues/120).
